name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - "**/*.sh"
      - compose.yaml
      - .trivyignore
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: cplieger/ci/.github/workflows/security-scan.yaml@e18b9a64157dea925d962be4265806b99e7f7680 # v2
